"""empty message

Revision ID: 1024572b282f
Revises: 
Create Date: 2020-05-08 11:45:49.958255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1024572b282f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('q_id', sa.Integer(), nullable=False),
    sa.Column('chapter_name', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('option_1', sa.String(), nullable=False),
    sa.Column('option_2', sa.String(), nullable=False),
    sa.Column('option_3', sa.String(), nullable=False),
    sa.Column('option_4', sa.String(), nullable=False),
    sa.Column('correct_option', sa.String(), nullable=False),
    sa.Column('question_mark', sa.Integer(), nullable=False),
    sa.Column('hint', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('q_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
