"""empty message

Revision ID: cc50d2da123b
Revises: 97a4633022ae
Create Date: 2020-03-01 14:21:07.946161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc50d2da123b'
down_revision = '97a4633022ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Question',
    sa.Column('q_id', sa.Integer(), nullable=False),
    sa.Column('chapter_name', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('option_1', sa.String(), nullable=False),
    sa.Column('option_2', sa.String(), nullable=False),
    sa.Column('option_3', sa.String(), nullable=False),
    sa.Column('option_4', sa.String(), nullable=False),
    sa.Column('correct_option', sa.String(), nullable=False),
    sa.Column('question_mark', sa.Integer(), nullable=False),
    sa.Column('hint', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('q_id')
    )
    op.drop_table('QuestionsTable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('QuestionsTable',
    sa.Column('q_id', sa.INTEGER(), server_default=sa.text('nextval(\'"QuestionsTable_q_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('chapter_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('option_1', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('option_2', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('option_3', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('option_4', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('correct_option', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('question_mark', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hint', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('q_id', name='QuestionsTable_pkey')
    )
    op.drop_table('Question')
    # ### end Alembic commands ###
